<?php
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;

function jugaad_patch_block_access(Block $block, $operation, AccountInterface $account) {
	
	if ($operation == 'view') {
		//kint($block);
		if($block->id() == 'scanhereonyourmobile') {
            $block->setRegion('sidebar');
            $block->save();
			//Now based on Node Pages, Hide the block
			$node = \Drupal::routeMatch()->getParameter('node');
			if (($node instanceof \Drupal\node\NodeInterface) && ($node->gettype() == 'product') )
			{
				// Show the block if the node is 'product' type
				return AccessResult::forbiddenIf(false)->addCacheableDependency($block);
			}

            return AccessResult::forbiddenIf(true)->addCacheableDependency($block);
		}
	}
}